/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f3ff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c3c0ff",
        "surface-dim": "#d2d9f4",
        "background": "#faf8ff",
        "surface-container-highest": "#dae2fd",
        "on-background": "#131b2e",
        "secondary-container": "#8a4cfc",
        "inverse-surface": "#283044",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#002114",
        "tertiary-container": "#006e4c",
        "surface-variant": "#dae2fd",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-tertiary-container": "#7df1bd",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#25005a",
        "secondary": "#712ae2",
        "inverse-on-surface": "#eef0ff",
        "secondary-fixed": "#eaddff",
        "on-surface": "#131b2e",
        "outline": "#777587",
        "on-primary-container": "#dad7ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#4f46e5",
        "primary": "#3525cd",
        "on-secondary-container": "#fffbff",
        "secondary-fixed-dim": "#d2bbff",
        "on-error": "#ffffff",
        "outline-variant": "#c7c4d8",
        "surface-container": "#eaedff",
        "on-surface-variant": "#464555",
        "on-tertiary-fixed-variant": "#005137",
        "surface-tint": "#4d44e3",
        "surface-container-high": "#e2e7ff",
        "on-primary-fixed": "#0f0069",
        "tertiary": "#005338",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#68dba9",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed": "#85f8c4",
        "surface": "#faf8ff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "stack-md": "16px",
        "gutter": "24px",
        "stack-xl": "48px",
        "container-max": "1280px",
        "stack-lg": "24px",
        "stack-sm": "8px",
        "stack-xs": "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
