/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#fff5f8",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#fbcfe8",
        "surface-dim": "#fce7f3",
        "background": "#fffafc",
        "surface-container-highest": "#fbcfe8",
        "on-background": "#131b2e",
        "secondary-container": "#ff8a3d",
        "inverse-surface": "#283044",
        "on-primary-fixed-variant": "#9f1239",
        "on-tertiary-fixed": "#700010",
        "tertiary-container": "#be185d",
        "surface-variant": "#fce7f3",
        "surface-bright": "#fffafc",
        "on-secondary-fixed-variant": "#9a3412",
        "on-tertiary-container": "#fbcfe8",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#431407",
        "secondary": "#ff8a3d",
        "inverse-on-surface": "#fff0f3",
        "secondary-fixed": "#ffedd5",
        "on-surface": "#131b2e",
        "outline": "#88747a",
        "on-primary-container": "#ffe4e6",
        "on-tertiary": "#ffffff",
        "primary-container": "#ff8a3d",
        "primary": "#ec4899",
        "on-secondary-container": "#fffbff",
        "secondary-fixed-dim": "#fed7aa",
        "on-error": "#ffffff",
        "outline-variant": "#e6d5dc",
        "surface-container": "#fff0f3",
        "on-surface-variant": "#4d4246",
        "on-tertiary-fixed-variant": "#9f1239",
        "surface-tint": "#ec4899",
        "surface-container-high": "#ffe4e6",
        "on-primary-fixed": "#4c0519",
        "tertiary": "#f43f5e",
        "on-secondary": "#ffffff",
        "inverse-primary": "#fbcfe8",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#fbcfe8",
        "primary-fixed": "#ffe4e6",
        "tertiary-fixed": "#fce7f3",
        "surface": "#fffafc"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "stack-md": "16px",
        "gutter": "24px",
        "stack-xl": "48px",
        "container-max": "1280px",
        "stack-lg": "24px",
        "stack-sm": "8px",
        "stack-xs": "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
